name: Check Markdown links

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-24.04

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check Markdown links
        uses: lycheeverse/lychee-action@v2.9.0
        with:
          args: >-
            --root-dir "${{ github.workspace }}"
            --offline
            --verbose
            --no-progress
            './README.md'
            './docs/**/*.md'
            './firmware/tests/README.md'
          fail: true
