name: Firmware tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  host-tests:
    name: Host unit & integration tests
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: firmware/tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0"
          bundler-cache: true
          working-directory: firmware/tests

      - name: Run Ceedling tests
        run: bundle exec ceedling test:all
